---
title: "Github"
format: html
editor: visual
---

Wir werden Github nutzen, um unsere Analyse-Repositorien zu speichern und zu teilen.

## Account erstellen

Erstelle ein Konto auf [Github](https://github.com/join). Nutze dabei deine *psy.lmu.de* oder *campus.lmu.de*-Adresse.

## Die LMU-GP2 Organisation

Alle Analyseprojekte werden in einem eigenen Git-Repositorium gespeichert. Um auf die Daten und Skripte der anderen zugreifen zu können, werden wir die Repositorien in der Github-Organisation [LMU-GP2](https://github.com/lmu-gp2) speichern.

::: callout-note
## Übungen

-   Bitte Moritz, Teil der Organisation zu werden
:::

## Verbinde RStudio mit Github

Um uns über Programme, wie RStudio mit Github verbinden zu können, brauchen wir einen Personal Access Token, den wir anstelle eine Passworts verwenden.

Erstelle Dir einen Token auf <https://github.com/settings/tokens/> und kopiere ihn zunächst in ein leeres Dokument (z.B. Editor).

Wenn wir gleich das erste Mal ein Projekt von Github klonen bzw. es abspeichern, gibst du einmalig den Token als Passwort ein. Auf diesem Rechner ist er dann gespeichert.

::: callout-tip
## Ressourcen

[Introduction to version Control in R with RStudio, Git, and Github](https://lmu-osc.github.io/Introduction-RStudio-Git-GitHub/) [Happy Git and GitHub for the useR](https://happygitwithr.com/)
:::
